/*
 * File: BuddyList.ui.js
 * Date: Tue Apr 13 2010 20:00:47 GMT-0400 (Eastern Daylight Time)
 * 
 * This file was generated by Ext Designer version xds-1.0.0.7c.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

BuddyListUi = Ext.extend(Ext.Window, {
	title : 'Online Buddies',
	width : 284,
	height : 389,
	modal : true,
	initComponent : function() {
		this.bbar = {
			xtype : 'toolbar',
			items : [ {
				xtype : 'tbseparator'
			}, {
				xtype : 'button',
				text : 'Refresh List',
				handler : function() {
					Connector.receive.request( {
						command : Command.GET_BUDDY_LIST
					});
					loader.displayLoader();
				}
			}, {
				xtype : 'tbseparator'
			}, {
				xtype : 'button',
				text : 'Invite Buddies'
			}, {
				xtype : 'tbseparator'
			} ]
		};
		this.items = [ {
			xtype : 'listview',
			title : 'My ListView',
			columnSort : false,
			store : buddyListStore,
			columns : [ {
				xtype : 'lvcolumn',
				header : 'Buddies',
				dataIndex : 'buddy',
				width : 1
			} ]
		} ];
		BuddyListUi.superclass.initComponent.call(this);
	}
});
