/*
 * File: CardLayout.ui.js
 * Date: Tue Apr 13 2010 20:04:09 GMT-0400 (Eastern Daylight Time)
 * 
 * This file was generated by Ext Designer version xds-1.0.0.7c.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CardLayoutUi = Ext.extend(Ext.Viewport, {
    layout: 'card',
    activeItem: 0,
    initComponent: function() {
        CardLayoutUi.superclass.initComponent.call(this);
    }
});
