/*
 * File: MyViewport.ui.js
 * Date: Wed Apr 14 2010 20:51:36 GMT-0400 (Eastern Daylight Time)
 * 
 * This file was generated by Ext Designer version xds-1.0.0.8.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyViewportUi = Ext.extend(Ext.Viewport, {
	layout : 'border',
	initComponent : function() {
		this.items = [ {
			xtype : 'panel',
			title : '',
			region : 'north',
			height : 51,
			border : false,
			tbar : {
				xtype : 'toolbar',
				items : [ {
					xtype : 'buttongroup',
					title : 'Chatroom Options',
					columns : 2,
					items : [ {
						xtype : 'button',
						id : 'InviteBuddiesID',
						text : 'Invite Buddies',
						disabled : true,
						handler : function() {
							Connector.receive.request( {
								command : Command.GET_BUDDY_LIST
							});
							loader.displayLoader();
						}
					}, {
						xtype : 'button',
						text : 'Sign out',
						id : 'LogoutId',
						handler : function() {
							Connector.receive.request( {
								command : Command.LOGOUT
							});
							loader.displayLoader();
						}
					} ]
				}, {
					xtype : 'buttongroup',
					title : 'Application Options',
					columns : 2,
					items : [ {
						id : 'CreateChatID',
						xtype : 'button',
						text : 'Create Chat',
						handler : function() {
							Connector.receive.request( {
								command : Command.CREATE_CHATROOM
							});
							loader.displayLoader();
						}
					}, {
						id : 'JoinChatID',
						xtype : 'button',
						text : 'Join Chat',
						handler : function() {
							Connector.receive.request( {
								command : Command.RETRIEVE_CHATROOMS
							});
							loader.displayLoader();
//							var chatroomList = new ChatroomListUi( {
//								id : 'chatroomListID',
//								closeAction : 'close'
//							});
//							chatroomList.show();
//							var message = 
//							{"message":"Retrieved chatrooms","requestId":"2","command":"createChatroom","success":"1","chatrooms":[{"name":"dbgotd@gmail.com","FBUserKey":"dbgotd@gmail.com"}]};
//							chatroomListStore.loadData(message);
						}
					} ]
				} /*
					 * , { xtype: 'buttongroup', title: 'Buttons', columns: 2,
					 * items: [ { xtype: 'button', text: 'Button 1' }, { xtype:
					 * 'button', text: 'Button 2' } ] }
					 */
				]
			}
		}, {
			xtype : 'panel',
			title : '',
			region : 'center',
			border : false,
			layout : 'auto',
			items : [ {
				xtype : 'panel',
				title : '',
				height : 107,
				layout : 'fit',
				region : 'center',
				border : false,
				items : [ {
					xtype : 'htmleditor',
					id: 'ChatInputBoxID',
					anchor : '100%',
					fieldLabel : 'Label',
					height : 150,
					width : 300
				} ],
				bbar : {
					xtype : 'toolbar',
					height : '',
					items : [ {
						xtype : 'tbseparator'
					}, {
						id : 'ClearID',
						xtype : 'button',
						text : 'Clear',
						disabled : true,
						handler : function() {
							alert('clear!');
						}
					}, {
						xtype : 'tbseparator'
					}, {
						id : 'SendID',
						xtype : 'button',
						text : 'Send',
						disabled : true,
						handler : function() {
							var chatOutput = document.getElementById('chatOutputBox');
							var chatInput = Ext.getCmp('ChatInputBoxID');
							// set the chat window to the new chat value
							// textContent removes the HTML, not good!
							chatOutput.innerHTML = chatOutput.innerHTML + '<br/>' + 
								'<span style="color:blue; font-weight:bold;">You:</span> ' + chatInput.getValue() + '<br/>';
							// erase the chat input value
//							chatInput.update('');
							Connector.receive.request( {
								command : Command.SEND_CHAT,
								data : {
									chatContent: chatInput.getValue()
//									userIds: ['100000977855031']
								}
							});
//							loader.displayLoader();
						}
					}, {
						xtype : 'tbseparator'
					} ]
				}
			}, {
				xtype : 'panel',
				title : '',
				id : 'ChatOutputBoxID',
				bodyBorder : true,
				height : 678,
				html: '<div id="chatOutputBox"></div>'
			} ]
		}, {
			xtype : 'panel',
			title : '',
			region : 'west',
			width : 275,
			border : false,
			items : [ {
				xtype : 'listview',
				title : 'My ListView',
				columnSort : false,
				store : chatroomMemberListStore,
				columns : [ {
					xtype : 'lvcolumn',
					header : 'Key',
					dataIndex : 'FBUserKey',
					width : .6
				}, {
					xtype : 'lvcolumn',
					header : 'Name',
					dataIndex : 'name',
					width : .4
				} ]
			} ]
		} ];
		MyViewportUi.superclass.initComponent.call(this);
	}
});
