/*
 * File: BuddyList.ui.js
 * Date: Tue Apr 13 2010 20:00:47 GMT-0400 (Eastern Daylight Time)
 * 
 * This file was generated by Ext Designer version xds-1.0.0.7c.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ChatroomListUi = Ext.extend(Ext.Window, {
    title: 'Available Chatrooms',
    width: 284,
    height: 389,
    modal: true,
    initComponent: function() {
        this.bbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    text: 'Refresh List',
                    handler: function(){
                       
                    }
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    text: 'Join Chatroom'
                },
                {
                    xtype: 'tbseparator'
                }
            ]
        };
        this.items = [
            {
                xtype: 'listview',
                title: 'My ListView',
                columnSort: false,
                store: chatroomListStore,
                columns: [
                    {
                        xtype: 'lvcolumn',
                        header: 'Key',
                        dataIndex: 'FBUserKey',
                        width: .5
                    },
                    {
                        xtype: 'lvcolumn',
                        header: 'Chatrooms',
                        dataIndex: 'chatroom',
                        width: .5
                    }
                ]
            }
        ];
        ChatroomListUi.superclass.initComponent.call(this);
    }
});
