/*
 * File: MyContainer.js
 * Date: Sun Apr 04 2010 12:26:19 GMT-0400 (Eastern Daylight Time)
 * 
 * This file was generated by Ext Designer version 1.0.0.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class. 
 */

MyContainer = Ext.extend(MyContainerUi, {
    initComponent: function() {
        MyContainer.superclass.initComponent.call(this);
    }
});
