/*
 * File: MyContainer.ui.js
 * Date: Sun Apr 04 2010 12:26:19 GMT-0400 (Eastern Daylight Time)
 * 
 * This file was generated by Ext Designer version 1.0.0.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file. 
 */

MyContainerUi = Ext.extend(Ext.Container, {
    autoEl: 'div',
    width: 226,
    height: 87,
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                title: '',
                labelWidth: 100,
                labelAlign: 'left',
                layout: 'form',
                bbar: {
                    xtype: 'toolbar',
                    items: [
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Create Room',
                            handler: function(){
                                var chatName = Ext.get('ChatName');
                                event.ChatroomCreate(chatName.getValue());
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Clear Fields'
                        },
                        {
                            xtype: 'tbseparator'
                        }
                    ]
                },
                items: [
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Chatroom name',
                        anchor: '100%',
                        name: 'ChatName',
                        id: 'ChatName'
                    }
                ]
            }
        ];
        MyContainerUi.superclass.initComponent.call(this);
    }
});
