/*
 * File: MyViewport.ui.js
 * Date: Tue Mar 30 2010 23:40:49 GMT-0400 (Eastern Daylight Time)
 * 
 * This file was generated by Ext Designer version 1.0.0.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file. 
 */

MyViewportUi = Ext.extend(Ext.Viewport, {
    layout: 'border',
    initComponent: function() {
        this.items = [
        {
            xtype: 'panel',
            title: 'Chatroom Activity',
            region: 'center',
            animCollapse: true,
            bodyBorder: false,
            layout: 'card',
            activeItem: 0
        },
        {
            xtype: 'panel',
            title: 'Chatroom Community',
            region: 'west',
           width: 211,
            collapsible: true,
            titleCollapse: false,
            layout: 'accordion',
            activeItem: 2,
            items: [
            {
                xtype: 'panel',
                title: 'Find Friends'
            },
            {
                xtype: 'panel',
                title: 'Create a Chatroom',
                items: [new MyContainerUi() ]
            },
            {
                xtype: 'panel',
                title: 'Search for Chatrooms'
            }
            ]
        }
        ];
        MyViewportUi.superclass.initComponent.call(this);
    }
});

